1. A) The Atbash cipher is an encryption method in which each letter of a word is replaced with its "mirror" letter in the alphabet: A <=> Z; B <=> Y; C <=> X; etc.

Create a function that takes a string and applies the Atbash cipher to it.


In [28]:
def cipher(s):
    return "".join(chr(155 - ord(c)) for c in s)

s = input("Enter string : ").upper()

print(f"cipher string : {cipher(s)}")

Enter string : absd
cipher string : ZYHW


B) An identity matrix is defined as a square matrix with 1s running from the top left of the square to the bottom right. The rest are 0s. The identity matrix has applications ranging from machine learning to the general theory of relativity.

Create a function that takes an integer n and returns the identity matrix of n x n dimensions. For this challenge, if the integer is negative, return the mirror image of the identity matrix of n x n dimensions.. It does not matter if the mirror image is left-right or top-bottom.


In [2]:
import numpy as np


def identity(n):
    mirror = n < 0 
    n = abs(n)

    m = np.matrix([
            [1 if i == j else 0 for j in range(n)] for i in range(n)
        ])


    return m if not mirror else m[::-1]

if __name__ == "__main__":
    n = int(input("Enter order of matrix : "))
    print(identity(n))

[[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]


2 a) Create a function that will recursively count the number of digits of a number. Conversion of the number to a string is not allowed, thus, the approach is recursive.
Example
digits_count(4666) ➞ 4
digits_count(544) ➞ 3


In [ ]:
def digit_count(n):
    return 1 if n < 10 else digit_count(int(n / 10)) + 1

n = int(input("Enter number : "))
print(f"no of digits : {digit_count(n)}")

B) A prison can be represented as a list of cells. Each cell contains exactly one prisoner. A 1 represents an unlocked cell and a 0 represents a locked cell.
[1, 1, 0, 0, 0, 1, 0]
Starting inside the leftmost cell, you are tasked with seeing how many prisoners you can set free, with a catch. You are the prisoner in the first cell. If the first cell is locked, you cannot free anyone. Each time you free a prisoner, the locked cells become unlocked, and the unlocked cells become locked again.
Create a function that, given this unique prison arrangement, returns the number of freed prisoners.
freed_prisoners([1, 1, 0, 0, 0, 1, 0]) ➞ 4

freed_prisoners([1, 1, 1]) ➞ 1

freed_prisoners([0, 0, 0]) ➞ 0

freed_prisoners([0, 1, 1, 1]) ➞ 0
Hint:
1. You are the prisoner in the first cell. You must be freed to free anyone else. 2. You must free a prisoner in order for the locks to switch. So in the second example where the input is [1, 1, 1] after you release the first prisoner, the locks change to [0, 0, 0]. Since all cells are locked, you can release no more prisoners.
