In [1]:
import numpy as np

1D array

In [6]:
a = np.array([1, 2, 3, 4, 5])

# accessing one index
print(a[0])

# index slicing 
# a[ start : end : step ]

print(a)
print(a[1])
print(a[[1, 2]])

[1 2 3 4 5]
2
[2 3]


In [16]:
# 2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [19]:

# accessing multiple elements
print(b[
    [0, 1], 
    [3, 2]
])

# an predefinded function will be called 
# returns an array consisting of b[0, 3] = 4, b[1, 2] = 7


[4 7]


In [22]:
# 3d array
c = np.array([
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]]
])

c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
c[
    [0, 0, 0], 
    [1, 1, 1], 
    [0, 1, 2]
]
# it will return array of c[0, 1, 0] = 4, c[0, 1, 1] = 5, c[0, 1, 2] = 6

array([4, 5, 6])